package model

// This code is generated by go generate with 
// genie cli. You may edit as you wish

import (
  "database/sql"
              "time"
)

type UserModel struct {
  DB *sql.DB
}

func (m *UserModel ) Insert() {
}
